name: Fix

on:
  pull_request:
    branches: main

jobs:
  fix:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:fix

      - uses: qoomon/actions--create-commit@v1
        id: actions--create-commit
        with:
          message: |
            🎨 pnpm run lint:fix
            github-actions[bot]
          skip-empty: true

      - if: ${{ steps.actions--create-commit.outputs.commit }}
        run: git push
