name: Fix

on:
  pull_request:
    branches: main

jobs:
  fix:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:fix

      - id: diff
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo 'changes=true' >>"$GITHUB_OUTPUT"
          fi

      - if: steps.diff.outputs.changes == 'true'
        name: Commit and push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git commit --all --message '🎨 pnpm run lint:fix' --message '[dependabot skip]'
          git push
